version: '3'
services:
  app:
    container_name: node_api_1
    restart: always
    build: .
    ports:
      - '80:3000'
    links:
      - db  
  db: 
    container_name: mongo_db_1
    image: mongo
    ports:
      - '27017:27017'
